import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = { title: "Technical Briefs | Control Lattice Systems", description: "Inspect demonstrated controls, diagnostics, digital twin, and hybrid-infrastructure work from Control Lattice Systems." };

export default function WorkPage() { return <main className="science-theme technical-page"><SiteHeader active="work"/>
  <section className="science-page-hero"><div className="shell"><p className="eyebrow"><i/> Demonstrated engineering</p><h1>Technical work you can inspect.</h1><p>Working controls, diagnostics, simulation and infrastructure examples—with clear boundaries between demonstrated capability and production deployment.</p></div></section>
  <section className="science-content shell"><div className="project-grid">
    <article className="project-card featured-project" id="sso"><img className="project-image screenshot" src="/source-stability-phoebus.png" alt="Phoebus Source Stability Observer interface showing measurements, correlations, and synchronized trends"/><div className="project-content"><div className="project-meta"><span>Public technical demonstrator</span><b>Source available</b></div><h2>Source Stability Observer</h2><p>A controls and diagnostics framework combining synchronized engineering measurements, portable C analytics, explicit data-quality gates, bounded statistics, EPICS integration, Phoebus visualization and deterministic simulation to investigate X-ray source variability.</p><div className="presentation-gallery"><img src="/observer-presentation-live.png" alt="Live Source Stability Observer interface"/><img src="/observer-presentation-pipeline.png" alt="Acquisition and observer pipeline"/><img src="/observer-presentation-c-gate.png" alt="C quality-gate sequence"/><img src="/observer-presentation-signatures.png" alt="Simulated diagnostic signatures"/></div><div className="tags"><span>EPICS</span><span>C</span><span>PHOEBUS</span><span>DIAGNOSTICS</span></div><p><strong>Public source. Professional implementation.</strong> Hardware and detector integration, channel engineering, calibration, site configuration, validation, training and support are available as scoped engagements.</p><div className="project-links"><a className="text-link" href="https://github.com/Rainer1370/source-stability-observer" target="_blank" rel="noreferrer">Review the source ↗</a><a className="text-link" href="/contact?service=observer-integration">Discuss implementation →</a></div></div></article>
    <article className="project-card" id="timing"><img className="project-image screenshot" src="/timing-sim-gui.png" alt="Accelerator timing digital twin interface"/><div className="project-content"><div className="project-meta"><span>Public working simulation</span></div><h2>Accelerator Timing Digital Twin</h2><p>An EPICS-based timing simulation modeling environmental phase drift, master-oscillator and laser behavior, adaptive PID correction, Phoebus operation and beam-dump logic.</p><div className="tags"><span>EPICS</span><span>PYTHON</span><span>PID</span><span>TIMING</span></div><p>Suitable as a starting point for timing studies, controls development, operator training and customer-specific digital-twin adaptation.</p><a className="text-link" href="https://github.com/Rainer1370/TimingSim" target="_blank" rel="noreferrer">View the public project ↗</a></div></article>
    <article className="project-card" id="azure"><div className="project-content"><div className="project-meta"><span>Reference implementation</span></div><h2>Azure Hybrid Operations Lab</h2><p>A deployment-oriented reference implementation for centralized logs, monitoring, inventory and secure hybrid management while keeping deterministic controls on premises.</p><div className="azure-flow compact"><div><small>ON PREMISES</small><strong>Controls + servers</strong></div><b>→</b><div><small>CONTROL PLANE</small><strong>Azure Arc</strong></div><b>→</b><div><small>OPERATIONS</small><strong>Azure Monitor</strong></div></div><div className="tags"><span>AZURE ARC</span><span>MONITOR</span><span>LINUX</span><span>VMWARE</span><span>BICEP</span></div><a className="text-link" href="https://github.com/Rainer1370/Controllattice-systems/tree/main/azure-hybrid-operations-lab" target="_blank" rel="noreferrer">Review the implementation ↗</a></div></article>
    <article className="project-card"><img className="project-image fusion-image" src="/fusion-stellarator-exploded-view.jpg" alt="Exploded technical view of a stellarator"/><div className="project-content"><div className="project-meta"><span>Public architecture · rights reserved</span></div><h2>Fusion Digital Twin DCS</h2><p>A facility-scale reference architecture connecting plant systems, deterministic controls, EPICS supervisory integration, timing, archiving, replay, estimation, optimization and operator workflows.</p><div className="tags"><span>FUSION</span><span>DIGITAL TWIN</span><span>DCS</span><span>VIRTUAL COMMISSIONING</span></div><p><strong>The architecture is public; deployment-grade implementation is reserved.</strong></p><a className="text-link" href="https://github.com/Rainer1370/fusion-digital-twin-dcs" target="_blank" rel="noreferrer">Review the technical preview ↗</a></div></article>
  </div></section><section className="contact"><div className="shell"><p className="eyebrow"><i/> Apply the architecture</p><h2>Bring us the system that needs clarity.</h2><a className="button light" href="/contact">Start a conversation ↗</a></div></section><SiteFooter/></main>; }
