import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = { title: "About | Control Lattice Systems", description: "Learn how Control Lattice Systems connects controls, infrastructure, simulation, and technical knowledge under the leadership of Rob Rainer." };

export default function AboutPage() { return <main className="about-page">
  <SiteHeader active="about" />
  <section className="about-hero shell"><p className="eyebrow"><i/> About Control Lattice</p><h1>Engineering that makes<br/><em>complexity navigable.</em></h1><p className="lede">Control Lattice Systems is an independent engineering practice connecting physical equipment, control software, infrastructure, simulation, and the knowledge people need to operate them well.</p></section>
  <section className="about-story shell"><div className="quote">“The value is not another isolated tool. It is a system people can understand, trust, and improve.”</div><div><p className="eyebrow"><i/> The practice</p><h2>Built across the gaps.</h2><p>Many difficult technical problems do not belong to one discipline. They appear where instruments meet software, deterministic controls meet enterprise infrastructure, operational data meets engineering judgment, or critical knowledge remains trapped in documents and individual experience.</p><p>Control Lattice works in those intersections. Engagements can begin with a defined product, a system assessment, a working prototype, or an embedded engineering relationship.</p></div></section>
  <section className="principles shell"><div className="section-head"><div><p className="eyebrow"><i/> Operating principles</p><h2>Practical by design.</h2></div><p>Every engagement is bounded by the evidence available, the risks involved, and the decisions the work must support.</p></div><div className="principle-grid"><article><span>01</span><h3>Start with the system</h3><p>Understand equipment, interfaces, workflows, constraints, and ownership before prescribing a platform.</p></article><article><span>02</span><h3>Make evidence visible</h3><p>Use diagnostics, simulation, documentation, and clear acceptance criteria to support sound decisions.</p></article><article><span>03</span><h3>Keep people accountable</h3><p>Automation can increase capacity, but engineering commitments and final judgment remain human responsibilities.</p></article></div></section>
  <section className="leader shell"><div className="leader-mark" aria-hidden="true">RR</div><div className="leader-copy"><p className="eyebrow"><i/> Leadership</p><h2>Rob Rainer</h2><h3>Managing Director &amp; Principal Engineer</h3><p>Rob is a controls and systems engineering leader with more than 20 years of experience across scientific facilities, accelerator operations, advanced instrumentation, industrial automation, resilient computing infrastructure, and multidisciplinary technical leadership.</p><p>His background includes EPICS control systems, precision motion, diagnostics, virtualization, data-center infrastructure, Azure virtual machines, digital twins, and practical AI-supported engineering workflows.</p><div className="leader-actions"><a className="button" href="https://rainer1370.com" target="_blank" rel="noreferrer">View Rob’s engineering portfolio ↗</a><a className="text-link" href="/staff">Meet the staff →</a></div></div></section>
  <section className="contact"><div className="shell"><p className="eyebrow"><i/> Start with the problem</p><h2>Bring us the system that needs clarity.</h2><a className="button light" href="/contact">Start a conversation ↗</a></div></section>
  <SiteFooter />
</main>; }
