const services=[
 ["01","Controls & instrumentation","Architecture, integration, diagnostics, EPICS, operator interfaces, digital twins, and modernization for scientific and industrial systems."],
 ["02","AI & technical knowledge","Practical AI workflows that turn fragmented procedures, engineering records, and system data into trustworthy, usable knowledge."],
 ["03","Managed technical systems","Ongoing engineering and IT support for organizations that need continuity without adding a full-time specialist to payroll."]
];
const plans=[
 ["Systems Care","Essential continuity",["Monthly systems review","Issue and risk register","Documentation upkeep","Priority advisory access"]],
 ["Controls & Knowledge Care","Integrated support",["Controls and data review","AI-ready knowledge organization","Operational documentation","Monthly improvement cycle"]],
 ["Embedded Technical Partner","Deeper engagement",["Scheduled engineering hours","Architecture and roadmap support","Vendor and team coordination","Custom reporting cadence"]]
];
function Mark(){return <svg className="mark" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 5 88 27v46L50 95 12 73V27Z"/><path d="M64 29a27 27 0 1 0 0 42M48 26v48l27 15M48 50l40-23"/><circle cx="48" cy="50" r="4"/><circle cx="88" cy="27" r="3"/><circle cx="75" cy="89" r="3"/></svg>}
function Brand(){return <span className="brand"><Mark/><span><strong>CONTROL<i>LATTICE</i></strong><small>SYSTEMS</small></span></span>}
export default function Home(){return <main>
 <header className="nav shell"><a href="#top" aria-label="ControlLattice Systems home"><Brand/></a><nav><a href="#services">Services</a><a href="#care">Systems Care</a><a href="#work">Work</a><a href="#about">About</a></nav><a className="button small" href="#contact">Start a conversation</a></header>
 <section className="hero shell" id="top"><div><p className="eyebrow"><i/> Controls · AI · Technical Knowledge</p><h1>Complex systems.<br/><em>Usable knowledge.</em></h1><p className="lede">ControlLattice connects controls engineering, intelligent tooling, and technical knowledge so complex operations become easier to understand, maintain, and improve.</p><div className="actions"><a className="button" href="#contact">Discuss your system ↗</a><a className="text-link" href="#services">Explore capabilities ↓</a></div><div className="signal"><span>CONTROL</span><b/><span>CONTEXT</span><b/><span>KNOWLEDGE</span></div></div><div className="hero-visual" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="beam b1"/><div className="beam b2"/><div className="beam b3"/><Mark/><span className="node n1"/><span className="node n2"/><span className="node n3"/></div></section>
 <section className="section shell" id="services"><div className="section-head"><div><p className="eyebrow"><i/> Connected capabilities</p><h2>Engineering across the gaps.</h2></div><p>Many technical problems live between disciplines. We work where equipment meets software, data meets decisions, and documentation meets real operations.</p></div><div className="service-grid">{services.map(s=><article key={s[0] as string}><span>{s[0]}</span><div className="mini-icon">⌁</div><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>
 <section className="audit-wrap"><div className="audit shell"><div><p className="eyebrow"><i/> A practical starting point</p><h2>The Engineering Knowledge Audit</h2><p>Before adding another tool, we map how your system knowledge actually moves: what is documented, what lives with individuals, where operators lose time, and where automation can safely help.</p><a className="button" href="#contact">Ask about an audit ↗</a></div><ol><li><b>01</b><span><strong>Observe</strong>Systems, workflows, and pain points</span></li><li><b>02</b><span><strong>Map</strong>Controls, data, documents, and ownership</span></li><li><b>03</b><span><strong>Prioritize</strong>Improvements by value and risk</span></li><li><b>04</b><span><strong>Connect</strong>A practical technical roadmap</span></li></ol></div></section>
 <section className="section shell" id="care"><div className="section-head"><div><p className="eyebrow"><i/> Subscription engineering</p><h2>Continuity, not just consulting.</h2></div><p>Recurring support keeps small issues from becoming urgent projects. Each engagement is scoped around the system, response expectations, and engineering capacity required.</p></div><div className="plan-grid">{plans.map((p,i)=><article className={i===1?"featured":""} key={p[0] as string}>{i===1&&<span className="flag">Most complete</span>}<small>{p[1] as string}</small><h3>{p[0] as string}</h3><p>{i===0?"A recurring technical check-in for smaller systems, documentation, and IT operations.":i===1?"Controls engineering and knowledge management working as one service—not separate silos.":"Reserved engineering capacity for complex programs needing steady technical leadership."}</p><ul>{(p[2] as string[]).map(x=><li key={x}>{x}</li>)}</ul><a href="#contact">Build a scope →</a></article>)}</div><p className="fineprint">Plans are tailored after an initial technical conversation. No artificial tiers, surprise scope, or promises of 24/7 coverage.</p></section>
 <section className="work shell" id="work"><div><p className="eyebrow"><i/> Demonstrated engineering</p><h2>Source Stability Observer</h2><p>A portable controls and diagnostics demonstrator combining synchronized measurements, bounded statistics, EPICS integration, Phoebus visualization, simulation, and explicit data-quality gating.</p><div className="tags"><span>EPICS</span><span>C</span><span>PHOEBUS</span><span>DIAGNOSTICS</span></div><a className="text-link" href="https://github.com/Rainer1370/source-stability-observer" target="_blank" rel="noreferrer">View the open project ↗</a></div><div className="scope"><span>ASSOCIATION LOGIC</span><div className="trace"><i/><i/><i/><i/><i/></div><dl><div><dt>Inputs</dt><dd>Synchronized engineering signals</dd></div><div><dt>Method</dt><dd>Quality gates + bounded statistics</dd></div><div><dt>Output</dt><dd>Evidence for the next experiment</dd></div></dl></div></section>
 <section className="about shell" id="about"><div className="quote">“Good engineering makes complexity navigable.”</div><div><p className="eyebrow"><i/> Technical leadership</p><h2>Rob Rainer</h2><h3>Managing Director & Principal Engineer</h3><p>ControlLattice Systems is an independent engineering practice built around controls, scientific systems, infrastructure, and the increasingly important work of making technical knowledge usable. The approach is hands-on, evidence-driven, and honest about what a system—or an AI tool—can actually prove.</p><a className="text-link" href="https://rainer1370.com" target="_blank" rel="noreferrer">View engineering portfolio ↗</a></div></section>
 <section className="contact" id="contact"><div className="shell"><p className="eyebrow"><i/> Start with the system</p><h2>What is getting lost between<br/>your equipment, data, and people?</h2><p>Tell us what you are operating, where the friction is, and what a better outcome would look like.</p><a className="button light" href="mailto:rainer1370@gmail.com?subject=ControlLattice%20Systems%20inquiry">Start a conversation ↗</a></div></section>
 <footer className="shell"><Brand/><p>Controls, AI & Technical Knowledge<br/><span>Connecting complex systems to usable knowledge.</span></p><p>© 2026 ControlLattice Systems</p></footer>
 </main>}
