import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = { title: "Practical AI | Control Lattice Systems", description: "Practical, human-reviewed AI workflows, documentation automation, and team training for technical organizations." };

export default function AIPage() { return <main className="science-theme ai-page"><SiteHeader active="ai"/>
  <section className="science-page-hero"><div className="shell"><p className="eyebrow"><i/> Practical AI for real work</p><h1>Less prompting.<br/><em>More useful work.</em></h1><p>Patient, secure implementation that helps professionals and technical teams use AI on the work they already do—without surrendering judgment or accountability.</p></div></section>
  <section className="science-content shell"><div className="section-head"><div><p className="eyebrow"><i/> Clear starting points</p><h2>Start with the work—not the tool.</h2></div><p>Each engagement is shaped around actual responsibilities, comfort level and information-sensitivity requirements.</p></div><div className="science-card-grid"><article className="science-card"><small>INDIVIDUAL</small><h3>AI Confidence Session</h3><p>A private 90-minute working session using real tasks and questions, with safety guidance and a reusable workflow.</p></article><article className="science-card featured"><small>SMALL BUSINESS</small><h3>AI Business Setup</h3><p>A focused workflow review followed by secure tool configuration, reusable prompts, templates and implementation follow-up.</p></article><article className="science-card"><small>TEAMS</small><h3>Team AI Workshop</h3><p>A practical two-hour session built around relevant demonstrations, hands-on exercises and responsible-use practices.</p></article></div></section>
  <section className="workflow-band"><div className="shell workflow-grid"><div><p className="eyebrow"><i/> Beyond training</p><h2>Turn repeated effort into a dependable workflow.</h2><p>We identify a recurring task, understand its risks and exceptions, then build a process that saves time consistently.</p></div><div className="workflow-list"><span>Field notes → professional reports</span><span>Meeting notes → actions and follow-ups</span><span>Scattered files → usable knowledge base</span><span>Routine research → structured briefings</span><span>Manual checklists → guided workflows</span></div></div></section>
  <section className="science-content shell"><div className="principle-grid"><article><span>01</span><h3>Useful before impressive</h3></article><article><span>02</span><h3>Secure before convenient</h3></article><article><span>03</span><h3>Human review by design</h3></article></div></section>
  <section className="contact"><div className="shell"><p className="eyebrow"><i/> Bring one frustrating task</p><h2>What work keeps taking longer than it should?</h2><a className="button light" href="/contact?interest=AI%20workflow%20or%20document%20automation">Start a conversation ↗</a></div></section><SiteFooter/></main>; }
