import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = {
  title: "Machine Observability Review & The Observable Machine",
  description: "Improve industrial machine diagnostics with a practical review of alarms, interlocks, commands, readbacks, sequence state, timestamps, logs, operator displays, and restart evidence.",
  keywords: ["machine observability","industrial machine diagnostics","controls engineering consulting","SCADA diagnostics","EPICS consulting","alarm management","interlock diagnostics","machine failure analysis"],
  alternates: { canonical: "/observable-machine" },
  openGraph: { title: "Can Your Machine Explain Why It Failed?", description: "A practical machine-observability assessment, free failure-evidence checklist, and field guide for controls teams.", url: "/observable-machine", type: "website" },
};

const evidence = [
  ["Commands and readbacks", "See what the system requested, what the equipment reported, and where they diverged."],
  ["Sequence and state", "Reconstruct the operating mode, transition, step, and permissive state surrounding a failure."],
  ["Time and causality", "Use synchronized timestamps and event ordering instead of relying on alarm-list position."],
  ["Interlocks and first-out evidence", "Preserve the initiating condition rather than only the downstream cascade."],
  ["Operating context", "Connect controls data with load, environment, configuration, maintenance, and operator actions."],
  ["Exportable records", "Give engineering, operations, and vendors a repeatable evidence package for comparison."],
];

export default function ObservableMachinePage() {
  const serviceJson = {"@context":"https://schema.org","@type":"Service",name:"Machine Observability Review",provider:{"@type":"Organization",name:"Control Lattice Systems",url:"https://controllattice.com"},areaServed:"US",description:"Remote engineering assessment of machine alarms, interlocks, commands, readbacks, event sequencing, timestamps, operator displays, log retention, and restart procedures.",offers:{"@type":"Offer",price:"1500",priceCurrency:"USD",url:"https://controllattice.com/contact?service=observability-review"}};
  const bookJson = {"@context":"https://schema.org","@type":"Book",name:"The Observable Machine",author:{"@type":"Person",name:"Rob Rainer"},about:["machine observability","controls engineering","industrial automation","complex systems"],url:"https://a.co/d/01XD6ab9"};
  return <main className="observable-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceJson)}}/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(bookJson)}}/>
    <SiteHeader active="observable" />
    <section className="observable-hero"><div className="shell observable-hero-grid"><div><p className="eyebrow"><i/> The Observable Machine</p><h1>Can your machine explain <em>why it failed?</em></h1><p className="lede">An alarm identifies where a system noticed trouble. Diagnosis requires sequence, state, timing, interlocks, commands, readbacks, configuration, and physics.</p><div className="actions"><a className="button" href="/contact?service=observability-review&utm_source=youtube&utm_medium=organic&utm_campaign=observable_machine">Request a machine review →</a><a className="button ghost" href="#checklist">Get the free checklist ↓</a></div></div><aside className="observable-proof"><small>FIELD-GROUNDED ENGINEERING</small><strong>20+ years</strong><p>Scientific facilities, accelerators, X-ray systems, industrial controls, EPICS, SCADA, motion, instrumentation, commissioning, and operations.</p></aside></div></section>
    <section className="evidence-band"><div className="shell"><div className="section-head"><div><p className="eyebrow"><i/> Detection is not diagnosis</p><h2>The evidence a diagnosable machine preserves.</h2></div><p>Observability is not another dashboard. It is the deliberate ability to reconstruct what the machine was asked to do, what it actually did, and why the two separated.</p></div><div className="evidence-grid">{evidence.map((item,i)=><article key={item[0]}><small>0{i+1}</small><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></div></section>
    <section className="review-band"><div className="shell review-grid"><div><p className="eyebrow"><i/> Defined consulting package</p><h2>Machine Observability Review</h2><p>A practical remote assessment for teams losing time to intermittent faults, ambiguous alarms, incomplete logs, difficult restarts, or disagreements about what actually happened.</p><ul><li>Alarm, interlock, permissive, command, and readback review</li><li>Sequence-state and timestamp assessment</li><li>Operator-display and failure-workflow review</li><li>Log retention, comparison, and exportability assessment</li><li>Prioritized written recommendations</li><li>60-minute findings meeting</li></ul></div><aside className="review-offer"><small>DEFINED STARTING SCOPE</small><strong>$1,500</strong><span>Remote engineering review</span><p>The exact scope, source materials, confidentiality needs, and delivery schedule are confirmed before work begins. Expanded implementation is quoted separately.</p><a className="button" href="/contact?service=observability-review&utm_source=youtube&utm_medium=organic&utm_campaign=observable_machine">Discuss your system →</a></aside></div></section>
    <section className="checklist-band" id="checklist"><div className="shell checklist-grid"><div><p className="eyebrow"><i/> Free field resource</p><h2>Machine Failure Evidence Checklist</h2><p>A concise checklist for operators, technicians, and controls engineers to capture useful evidence before resetting, restarting, or changing the system.</p><a className="button light" href="/downloads/control-lattice-machine-failure-evidence-checklist.pdf" download>Download the free PDF →</a></div><div className="checklist-preview"><b>Before you reset:</b><span>Capture time, mode, step, first-out condition, active interlocks, commands, readbacks, recent changes, environmental state, screenshots, and exportable logs.</span></div></div></section>
    <section className="book-band"><div className="shell book-grid"><div><p className="eyebrow"><i/> Practical field guide</p><h2><em>The Observable Machine</em></h2><p>Principles and anecdotes of complex systems for technicians and operators, by Rob Rainer. The book connects controls architecture, diagnostics, interlocks, real-time behavior, FMEA, EPICS, commissioning, operations, and organizational learning.</p><div className="actions"><a className="button" href="https://a.co/d/01XD6ab9" target="_blank" rel="noreferrer">View the book on Amazon ↗</a><a className="text-link" href="https://www.youtube.com/@ControlLattice" target="_blank" rel="noreferrer">Watch Control Lattice on YouTube →</a></div></div><aside><blockquote>“Detection is not diagnosis.”</blockquote><p>Build systems that leave enough evidence for people to understand them.</p></aside></div></section>
    <section className="presence-wrap"><div className="presence shell"><div><p className="eyebrow"><i/> Organizational use</p><h2>A practical primer for every technical division.</h2><p>Complex organizations often teach equipment, procedures, controls, data, and failure analysis in separate channels. <em>The Observable Machine</em> gives technicians, operators, engineers, managers, and adjacent teams a common language for setpoints, feedback, interlocks, timing, configuration, data quality, alarms, causality, and recovery.</p><a className="button" href="/contact?service=division-primer">Discuss a Division Primer ↗</a></div><div className="presence-options"><article><small>TEAM STARTER</small><h3>Division Reading Cohort</h3><p>Provide the book across the division, then use one recent failure or difficult restart to identify where evidence, handoffs, and shared understanding break down.</p></article><article><small>FACILITATED OPTION</small><h3>Observer Workshop</h3><p>A 60–90 minute working session that maps a real event through condition, identify, align, gate, analyze, and present—ending with three practical improvements.</p></article></div></div></section>
    <section className="contact"><div className="shell"><p className="eyebrow"><i/> Start with the recurring problem</p><h2>Where does your team lose the evidence?</h2><p>Bring the fault, restart, alarm flood, intermittent behavior, or incomplete event record. We will help turn it into an observable engineering problem.</p><a className="button light" href="/contact?service=observability-review&utm_source=youtube&utm_medium=organic&utm_campaign=observable_machine">Request a review ↗</a></div></section>
    <SiteFooter />
  </main>;
}
